name: restapi_dart_frog
description: A new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_frog: ^1.1.0
  dart_odbc: ^2.0.3
  dotenv: ^4.2.0
  dart_jsonwebtoken: ^2.14.0
  bcrypt: ^1.1.3
  redis: ^4.0.0

dev_dependencies:
  dart_frog_lint: ^0.1.0
  mocktail: ^1.0.4
  test: ^1.25.5
